{application,eex,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir]},
              {description,"eex"},
              {modules,['Elixir.EEx','Elixir.EEx.Compiler',
                        'Elixir.EEx.Engine','Elixir.EEx.SmartEngine',
                        'Elixir.EEx.SyntaxError']},
              {registered,[]},
              {vsn,"1.16.1"}]}.
